## **Creación Básica de Arrays**

In [1]:
import numpy as np

In [2]:
a = np.array(13)
print("type(a): ", type(a), "\n")
print("a:", a, sep = "\n")
a

type(a):  <class 'numpy.ndarray'> 

a:
13


array(13)

In [3]:
b = np.array([1, 2, 3, 4])
print("b:", b, sep = "\n")
b

b:
[1 2 3 4]


array([1, 2, 3, 4])

In [5]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("c:", c, sep = "\n")
c

c:
[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
print("d:", d, sep = "\n")
d

d:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [9]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## **Indexación Básica**

In [10]:
print("a= ", a)
print("b[2] = ", b[2])
print("c[1] = ", c[1])
print("d[1] = ", d[1])

a=  13
b[2] =  3
c[1] =  [5 6 7 8]
d[1] =  [[ 9 10 11 12]
 [13 14 15 16]]


In [11]:
print("a= ", a)
print("b[2] = ", b[2])
print("c[1, 2] = ", c[1, 2])
print("d[1, 0, 2] = ", d[1, 0, 2])

a=  13
b[2] =  3
c[1, 2] =  7
d[1, 0, 2] =  11


In [12]:
print(b[1:4])
print(c[1, 1:3])
print(d[1:3, 1:3, 0:2])

[2 3 4]
[6 7]
[[[13 14]]]


## **Diferentes tipos de datos en los Arrays**

In [13]:
frutas = np.array(['Manzana', 'Naranja', 'Uva'])
print(frutas.dtype)

<U7


In [14]:
number_to_string = np.array([6, 1, 2, 4, 623, 8], dtype='str')
print(number_to_string.dtype)
print(number_to_string)

<U3
['6' '1' '2' '4' '623' '8']


In [15]:
try:
  error_array = np.array(['a', '2', '3'], dtype='int')

except:
  print("Hay un error en su lógica")

Hay un error en su lógica


In [17]:
float_array = np.array([1.1, 2.1, 3.1])

int_array = float_array.astype(int)
print(int_array)

[1 2 3]


In [20]:
vector = np.array([127, -127, 32767, -32767], dtype=np.int8) #Entero de un 1byte = 8bits (un bit necesario para almacenar el signo)
print("vector: \t", vector)
print("vector.dtype: \t", vector.dtype)

vector = np.array([127, -127, 32767, -32767], dtype=np.int16) #Entero de un 2bytes = 16bits (un bit necesario para almacenar el signo)
print("vector: \t", vector)
print("vector.dtype: \t", vector.dtype)

vector: 	 [ 127 -127   -1    1]
vector.dtype: 	 int8
vector: 	 [   127   -127  32767 -32767]
vector.dtype: 	 int16


<ipython-input-20-104165835021>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 32767 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  vector = np.array([127, -127, 32767, -32767], dtype=np.int8) #Entero de un 1byte = 8bits (un bit necesario para almacenar el signo)
<ipython-input-20-104165835021>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -32767 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  vector = np.array([127, -127, 32767, -32767], dtype=np.int8) #Entero de un 1byte = 8bits (un bit necesario para almacenar el signo)


## **Tamaño de los arrays**



In [21]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(4,)
(2, 4)
(2, 2, 4)


**Cambio de forma de los arreglos**

In [22]:
print("c = ", c, "\n")
c_1D = c.reshape(1, 8)
print("c_1D = ", c_1D, "\n")

c =  [[1 2 3 4]
 [5 6 7 8]] 

c_1D =  [[1 2 3 4 5 6 7 8]] 



In [23]:
c_4D = c.reshape(4, 2)
print("c_4D = ", c_4D, "\n")

c_4D =  [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



In [24]:
print(d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [25]:
try:
  d.reshape(3, 5)

except:
  print("Hay un error al intentar cambiar la forma del arreglo")

Hay un error al intentar cambiar la forma del arreglo


In [26]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**Transpuesta**

In [29]:
print("c = ", c, "\n")
print("c.T = ", c.T)

c =  [[1 2 3 4]
 [5 6 7 8]] 

c.T =  [[1 5]
 [2 6]
 [3 7]
 [4 8]]


## **Recorrer los valores de un arreglo**

In [30]:
for x in b:
  print(x, "\n")

1 

2 

3 

4 



In [31]:
for x in c:
  print(x, "\n")

[1 2 3 4] 

[5 6 7 8] 



In [32]:
for x in d:
  print(x, "\n")

[[1 2 3 4]
 [5 6 7 8]] 

[[ 9 10 11 12]
 [13 14 15 16]] 



In [33]:
for x in d:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [34]:
for x in np.nditer(d):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [35]:
for i, x in np.ndenumerate(d):
  print("i : ", i, "\t\tx:", x)

i :  (0, 0, 0) 		x: 1
i :  (0, 0, 1) 		x: 2
i :  (0, 0, 2) 		x: 3
i :  (0, 0, 3) 		x: 4
i :  (0, 1, 0) 		x: 5
i :  (0, 1, 1) 		x: 6
i :  (0, 1, 2) 		x: 7
i :  (0, 1, 3) 		x: 8
i :  (1, 0, 0) 		x: 9
i :  (1, 0, 1) 		x: 10
i :  (1, 0, 2) 		x: 11
i :  (1, 0, 3) 		x: 12
i :  (1, 1, 0) 		x: 13
i :  (1, 1, 1) 		x: 14
i :  (1, 1, 2) 		x: 15
i :  (1, 1, 3) 		x: 16


## **Generacion de arreglos**

In [36]:
print(f"np.arrange(0, 1, 0.1) :\n{np.arange(0, 1, 0.1)}")

np.arrange(0, 1, 0.1) :
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [38]:
print(f"np.zeros((2, 3, 5)) :\n{np.zeros((2, 3, 5))}")

np.zeros((2, 3, 5)) :
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [39]:
print(f"np.ones((2, 3, 5)) :\n{np.ones((2, 3, 5))}")

np.ones((2, 3, 5)) :
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [41]:
print(f"np.full((3, 4), 1.23) :\n{np.full((2, 3, 5), 1.23)}")

np.full((3, 4), 1.23) :
[[[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]

 [[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]]


In [42]:
print(f"np.identity(3) :\n{np.identity(3)}")

np.identity(3) :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
print(f"np.eye(3) :\n{np.eye(3)}")

np.eye(3) :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
print(f"np.empty((2, 3, 5)) :\n{np.empty((2, 3, 5))}")

np.empty((2, 3, 5)) :
[[[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]

 [[1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]
  [1.23 1.23 1.23 1.23 1.23]]]


**Operaciones don arrays**

In [46]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = np.where(vector%3 == 0)
print(f"type(indx) :\t{type(index)}")
print(f"indx :\t{index}")

type(indx) :	<class 'tuple'>
indx :	(array([2, 5, 8]),)


In [47]:
filtrado = vector[index]
print(f"filtrado :\t{filtrado}")

filtrado :	[3 6 9]


In [48]:
vector_bool = vector%3 == 0
print(f"type(vector_bool) :\t{type(vector_bool)}")
print(f"vector_bool :\t{vector_bool}")
filtrado = vector[vector_bool]
print(f"filtrado :\t{filtrado}")

type(vector_bool) :	<class 'numpy.ndarray'>
vector_bool :	[False False  True False False  True False False  True]
filtrado :	[3 6 9]


In [50]:
import math

opt1 = [math.sin(i) for i in [1, 2, 3]]
print(opt1)

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]


In [51]:
import math

opt1 = [math.sin(i) for i in [1, 2, 3]]
print(f"opt1 :\t{opt1}")
print(f"opt1[0] :\t{opt1[0]:.30f}")

opt1 :	[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]
opt1[0] :	0.841470984807896504875657228695


In [53]:
opt2 = np.sin(np.array([1, 2, 3], dtype=np.uint8), dtype=np.float64)
print(f"opt2 :\t{opt2}")
print(f"opt2[0] :\t{opt2[0]:.30f}")

opt2 :	[0.84147098 0.90929743 0.14112001]
opt2[0] :	0.841470984807896504875657228695


In [54]:
x = np.array([1, 2, 3])
y = np.array([0.0, 0.0, 0.0])
np.sin(x, where = x%2==1, out=y)
print(f"y : \t{y}")

y : 	[0.84147098 0.         0.14112001]


In [55]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 5, 6, 7])
z = np.add(x, y)
print(f"z : \t{z}")

z : 	[ 5  7  9 11]


In [56]:
z = x + y
print(f"z : \t{z}")

z : 	[ 5  7  9 11]


In [57]:
z = np.add(x, y, dtype=float)
print(f"z : \t{z}")

z : 	[ 5.  7.  9. 11.]


In [63]:
try:
  print(np.array([1, 2, 3, 4]) + np.array([5, 6]))
except:
  print("No se pude realizar la operación")

No se pude realizar la operación


In [64]:
try:
  print(np.array([1, 2, 3, 4]) + 0.9)
except:
  print("No se pude realizar la operación")

[1.9 2.9 3.9 4.9]


In [66]:
matriz = np.array([[3, 2, 4], [5, 2, 1], [8, 7, 6]])
print(f"matriz :\n{matriz}")
print(f"np.prod(matriz) :\n{np.prod(matriz)}")
print(f"np.prod(matriz, axis=0) :\n{np.prod(matriz, axis=0)}")
print(f"np.prod(matriz, axis=1) :\n{np.prod(matriz, axis=1)}")

matriz :
[[3 2 4]
 [5 2 1]
 [8 7 6]]
np.prod(matriz) :
80640
np.prod(matriz, axis=0) :
[120  28  24]
np.prod(matriz, axis=1) :
[ 24  10 336]


In [67]:
print(f"matriz :\n{matriz}")
print(f"np.cumprod(matriz) :\n{np.cumprod(matriz)}")
print(f"np.cumprod(matriz, axis=0) :\n{np.cumprod(matriz, axis=0)}")
print(f"np.cumprod(matriz, axis=1) :\n{np.cumprod(matriz, axis=1)}")

matriz :
[[3 2 4]
 [5 2 1]
 [8 7 6]]
np.cumprod(matriz) :
[    3     6    24   120   240   240  1920 13440 80640]
np.cumprod(matriz, axis=0) :
[[  3   2   4]
 [ 15   4   4]
 [120  28  24]]
np.cumprod(matriz, axis=1) :
[[  3   6  24]
 [  5  10  10]
 [  8  56 336]]


In [68]:
print(f"media: {np.mean(matriz)}")
print(f"desviación estandar muestral: {np.std(matriz, ddof=1)}")

media: 4.222222222222222
desviación estandar muestral: 2.438123139721299


**Multiplicación Matricial**

In [69]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[6, 5, 4],
                 [3, 2, 1]])

In [71]:
print(arr1 @ arr2.T)

[[28 10]
 [73 28]]


In [72]:
print(np.matmul(arr1, arr2.T))

[[28 10]
 [73 28]]


In [73]:
print(np.dot(arr1, arr2.T))

[[28 10]
 [73 28]]


In [74]:
try:
  print(0.9 @ arr1)
except:
  print("No se puede realizar la operación")

No se puede realizar la operación


In [75]:
try:
  print(np.array([0.9]) @ arr1)
except:
  print("No se puede realizar la operación")

No se puede realizar la operación


In [76]:
try:
  print(np.array([200, 100]) @ arr1)
except:
  print("No se puede realizar la operación")

[ 600  900 1200]


In [79]:
try:
  print(np.matmul(arr1, np.array([10, 20, 30])))
except:
  print("No se puede realizar la operación")

[140 320]
